<?php /** @var \Manugentoo\PartnerPortal\Block\Vip\Index $block */ ?>

<div class="content">
    <div class="grid-x">
        <div class="cell large-6 medium-8 small-12 large-offset-3 page-header text-center">
            <h1><?=('EXCLUSIVE')?></h1>
            <p><?=('Poly Pricing')?> - <?=$block->getPartner()->getName()?></p>
			<?php if($partnerImage = $block->getPartnerHeaderImage()):?>
                <img src="<?=$partnerImage?>" />
			<?php endif ?>
			<?php if($clientImage = $block->getClientHeaderImage()):?>
                <img src="<?=$clientImage?>" />
			<?php endif ?>
        </div>
    </div>
    <div class="grid-x">
        <div class="cell large-6 medium-8 small-12 large-offset-3 text-center">
            <div class="form">
                <p><?=__('Simply enter your work email address to access your recommended products and special pricing.')?></p>
                <form action="<?=$block->getOtpActionUrl()?>" method="post">
                    <input name="form_key" type="hidden" value="<?=$block->getFormKey();?>"/>
                    <input type="hidden" name="partner_url" value="<?=$block->getPartner()->getUrl()?>"/>
                    <input type="text" name="email" placeholder="Please enter your email.."/>
                    <button class="button green full-width bold">Submit</button>
                </form>
            </div>
            <p>Prefer to speak directly to our headsets team? <span class="phone-number">Ring <a href="tel:<?=Data::_DEFAULT_STORE_PHONE?>"class="ring"><?=Data::_DEFAULT_STORE_PHONE?></a></span> </p>
        </div>
    </div>
</div>