<?php /** @var \Manugentoo\PartnerPortal\Block\Vip\OtpVerifyForm $block */?>

<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper"><?=('Exclusive Pricing')?> - <?=$block->getPartner()->getName()?></span>
    </h1>
</div>
<div class="form-verify-otp">
    <p><?=__('Please check your email for your One Time Password, valid only for one visit.')?></p>
    <form class="form" action="<?=$block->getActionUrl()?>" method="post" id="form-otp">
        <fieldset class="fieldset">
            <input name="form_key" type="hidden" value="<?=$block->getFormKey();?>"/>
            <input type="hidden" name="partner_url" value="<?=$block->getPartner()->getUrl()?>"/>
            <input type="hidden" name="partner_email" value="<?=$block->getPartner()->getEmail()?>"/>
            <input type="hidden" placeholder="Enter OTP" name="otp_code" alt="otp" id="otpCode" class="input-text" data-validate="{required:true}">
            <div class="field">
                <div class="otp-codes">
                    <input type="number" alt="otp1" id="otp1" data-next="otp2" class="input-text text-center otp-field" autocomplete="off" maxlength="1" data-validate="{required:true}">
                    <input type="number" alt="otp2" id="otp2" data-next="otp3" data-previous="otp1" class="input-text text-center otp-field" autocomplete="off" maxlength="1" data-validate="{required:true}">
                    <input type="number" alt="otp3" id="otp3" data-next="otp4" data-previous="otp2" class="input-text text-center otp-field" autocomplete="off" maxlength="1" data-validate="{required:true}">
                    <input type="number" alt="otp4" id="otp4" data-next="otp5" data-previous="otp3" class="input-text text-center otp-field" autocomplete="off" maxlength="1" data-validate="{required:true}">
                    <input type="number" alt="otp5" id="otp5" data-next="otp6" data-previous="otp4" class="input-text text-center otp-field" autocomplete="off" maxlength="1" data-validate="{required:true}">
                    <input type="number" alt="otp6" id="otp6" data-previous="otp5" class="input-text text-center otp-field" autocomplete="off" maxlength="1" data-validate="{required:true}">
                </div>
            </div>
            <div class="field">
                <div class="primary">
                    <button id="otp-submit" type="submit" class="action submit primary" Title="Verify OTP Code">
                        <span>Verify OTP Code</span>
                    </button>
                </div>
            </div>
            <div class="field">
                <a class="otp-resend" href="<?=$block->getResendOtpUrl()?>">Didn't received your OTP code? click here to resend.</a>
            </div>
        </fieldset>
    </form>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "otpForm": {
                "otpSubmitButton": "otp-submit",
                "otpInputFields" : "otp-field",
                "otpCode" : "otpCode"
            },
            "otpFormKeyUp": {
                "otpForm" : "form-otp"
            }
        }
    }
</script>