<?php

use Manugentoo\PartnerPortal\Block\Vip\Products;
use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Catalog\Model\Product;
use Magento\Framework\App\Action\Action;
use Magento\Framework\App\ObjectManager;

/** @var Products $block */
$pricing_helper = $this->helper('Magento\Framework\Pricing\Helper\Data');

$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
$objectManager      = ObjectManager::getInstance();

$iterator = 1;

$mediaUrl =  $objectManager = $block->getMediaUrl();

$viewMode         = 'list';
$imageDisplayArea = 'category_page_list';
$showDescription  = true;
$templateType     = ReviewRendererInterface::SHORT_VIEW;

$pos = $block->getPositioned();
?>
<?php if ( ! $_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= /* @escapeNotVerified */
			__('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
	<?= $block->getToolbarHtml() // todo make this work ?>
	<?= $block->getAdditionalHtml() ?>
    <div class="products wrapper <?= /* @escapeNotVerified */$viewMode ?> products-<?= /* @escapeNotVerified */$viewMode ?>">
        <ol class="products list items product-items">
			<?php /** @var $_product Product */ ?>
			<?php foreach ($_productCollection as $_product): ?>

                <li class="item product product-item">
                    <div class="product-item-info"
                         id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                         data-container="product-<?= /* @noEscape */ $viewMode ?>">
						<?php
						$productImage = $block->getImage($_product, $imageDisplayArea);
						if ($pos != null) {
							$position = 'left:' . $productImage->getWidth() . 'px;'
								. 'top:' . $productImage->getHeight() . 'px;';
						}
						?>
						<?php $productImage = $block->getImage($_product, $imageDisplayArea);?>
						<?php // Product Image ?>
                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
							<?php
							$imageBaseImageUrl = $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'category_page_grid')->getUrl();
							?>
                            <img class="product-image" src="<?php echo $imageBaseImageUrl; ?>"/>
                        </a>
                        <div class="product-item-details">
							<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
									<?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                                </a>
                            </strong>
							<?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
							<?= /* @noEscape */ $block->getProductPrice($_product) ?>
							<?= $block->getProductDetailsHtml($_product) ?>

                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                    <div class="actions-primary">
										<?php if ($_product->isSaleable()):?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form"
                                                  data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                                  action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                                  method="post">
												<?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                        class="action tocart primary"
                                                        disabled>
                                                    <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            </form>
										<?php else:?>
											<?php if ($_product->isAvailable()):?>
                                                <div class="stock available">
                                                    <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
											<?php else:?>
                                                <div class="stock unavailable">
                                                    <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
                                    </div>
									<?= strpos($pos, $viewMode . '-primary') ?
										/* @noEscape */ $secureRenderer->renderStyleAsTag(
											$position,
											'product-item-info_' . $_product->getId() . ' div.actions-primary'
										) : '' ?>
                                    <div data-role="add-to-links" class="actions-secondary">
										<?php if ($addToBlock = $block->getChildBlock('addto')): ?>
											<?= $addToBlock->setProduct($_product)->getChildHtml() ?>
										<?php endif; ?>
                                    </div>
									<?= strpos($pos, $viewMode . '-secondary') ?
										/* @noEscape */ $secureRenderer->renderStyleAsTag(
											$position,
											'product-item-info_' . $_product->getId() . ' div.actions-secondary'
										) : '' ?>
                                </div>
                            </div>

                        </div>
                    </div>
                </li>
			<?php endforeach; ?>
        </ol>
    </div>
	<?php
	if ( ! $block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */$_product->getSku() ?>"
                }
            }
        }
        </script>
	<?php endif; ?>
<?php endif; ?>

