<?php
use Manugentoo\StockUpdater\Helper\Stock;
use Manugentoo\PartnerPortal\Block\Vip\Products;
use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Catalog\Model\Product;
use Magento\Framework\App\Action\Action;
use Magento\Framework\App\ObjectManager;

/** @var Products $block */
$pricing_helper = $this->helper('Magento\Framework\Pricing\Helper\Data');

$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
$objectManager      = ObjectManager::getInstance();

/** @var  $stockHelper Stock */
$stockHelper = $objectManager->get(Manugentoo\StockUpdater\Helper\Stock::class);
$iterator = 1;

$mediaUrl =  $objectManager = $block->getMediaUrl();

$viewMode         = 'list';
$imageDisplayArea = 'category_page_list';
$showDescription  = true;
$templateType     = ReviewRendererInterface::FULL_VIEW;
?>
<?php if ( ! $_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= /* @escapeNotVerified */
			__('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <div class="grid-x">
        <div class="cell small-12">
			<?= $block->getToolbarHtml() ?>
        </div>
    </div>
	<?= $block->getAdditionalHtml() ?>
    <div class="grid-container full products wrapper <?= /* @escapeNotVerified */$viewMode ?> products-<?= /* @escapeNotVerified */$viewMode ?>">
        <ol class="grid-x grid-margin-x products list items product-items">
			<?php
			/** @var $_product Product */ ?>
			<?php foreach ($_productCollection as $_product): ?>

				<?php
				$price_msrp       = $_product->getMsrp();
				$price_final      = $_product->getFinalPrice();
				$price_discounted = $_product->getMsrp() - $_product->getFinalPrice();

				$objectManager = ObjectManager::getInstance();
				$product       = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
				$iterator++;
				?>

                <li class="cell small-12 large-6 item product product-item">
                    <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */$viewMode ?>">
                        <div class="grid-x product-short-info">
                            <div class="cell small-8 medium-9">
                                <div class="product-name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= /* @escapeNotVerified */
									   $_product->getProductUrl() ?>">
										<?= /* @escapeNotVerified */
										$_helper->productAttribute($product, $product->getName(), 'name') ?>
                                    </a>
                                </div>
                            </div>

							<?php if ($price_msrp): ?>
                                <div class="cell small-4 medium-3 text-right">
                                    <div class="rrp-right">
										<?php if ($price_msrp > 0): ?>
                                            <span>RRP: <?php echo $pricing_helper->currency($price_msrp, true, false); ?></span>
										<?php endif ?>
                                    </div>
                                </div>
							<?php endif ?>

                            <div class="cell small-12 medium-7">
								<?php $productImage = $block->getImage($_product, $imageDisplayArea);?>
								<?php // Product Image ?>
                                <a <?php echo $this->helper('WeltPixel\GoogleTagManager\Helper\Data')->addProductClick($_product, $iterator-1); ?> href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1" style="min-height: 264px">
									<?php
									$imageBaseImageUrl = $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'category_page_grid')->getUrl();
									$imageRollover = $_product->getResource()->getAttribute('rollover')->getFrontend()->getValue($product);
									$imageRolloverUrl = $this->helper('Magento\Catalog\Helper\Image')->init($product, 'category_page_grid_rollover')->getUrl();
									?>
                                    <img class="product-image-photo" src="<?php echo $imageBaseImageUrl; ?>" onmouseover="this.src='<?php echo ($imageRollover) ? $imageRolloverUrl : $imageBaseImageUrl ?>';" onmouseout="this.src='<?php echo $imageBaseImageUrl; ?>';" style="max-height: 264px;"/>
                                </a>
                            </div>

                            <div class="cell small-12 medium-5">
                                <div class="prices">
                                    <span class="price-final" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" content="<?php echo $price_final ?>">
                                        <span style="display:none" itemprop="priceCurrency" content="AUD"></span>
                                        <span style="display:none" itemprop="price" content="<?php echo $price_final ?>"></span>
                                        <?php if ($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE):?>
                                            <span>From:</span><br/>
										<?php else: ?>
                                            <span>Now:</span><br/>
										<?php endif ?>
                                        <span class="green"><?php echo $pricing_helper->currency($price_final, true, false); ?></span> <span>Inc GST</span>
                                    </span>

									<?php if ($price_discounted > 0): ?>
                                        <span class="price-save"> Save: <?php echo $pricing_helper->currency($price_discounted, true, false); ?> </span>
									<?php endif ?>
                                </div>

								<?php if ($_product->getFeaturesWireless()): ?>
                                    <div class="features">
										<?php echo strip_tags($_product->getFeaturesWireless(), "<ul><li>") ?>
                                    </div>
								<?php endif ?>
                            </div>

                            <div class="product-sell-tag">
								<?php $attributeValue = $product->getAttributeText("productselltag") ?>
								<?php  if ($attributeValue == 'New Model'): ?>
                                    <img src="<?php echo $block->getViewFileUrl('images/small/catalog/product/new-product-tag-bottom.png') ?>"/>
								<?php endif ?>
								<?php  if ($attributeValue == 'Staff Pick'): ?>
                                    <img src="<?php echo $block->getViewFileUrl('images/small/catalog/product/staff-pick-tag-bottom.png') ?>"/>
								<?php endif ?>
								<?php  if ($attributeValue == 'Best Seller'): ?>
                                    <img src="<?php echo $block->getViewFileUrl('images/small/catalog/product/best-seller-tag-bottom.png') ?>"/>
								<?php endif ?>
								<?php  if ($attributeValue == 'Red Hot'): ?>
                                    <img src="<?php echo $block->getViewFileUrl('images/small/catalog/product/red-hot-tag-bottom.png') ?>"/>
								<?php endif ?>
								<?php  if ($attributeValue == 'Pre Order'): ?>
                                    <img src="<?php echo $block->getViewFileUrl('images/small/catalog/product/preorder-product-tag-bottom.png') ?>"/>
								<?php endif ?>
                            </div>
                        </div>

                        <div class="grid-x">
                            <div class="cell small-12">
                                <div class="product details product-item-details">
									<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                    <div class="grid-x grid-margin-x align-middle">
                                        <div class="cell small-6">
											<?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                        </div>
                                        <div class="cell small-6 text-right">
											<?php if ($stockHelper->isProductQtySalable($_product)) : ?>
												<?php
												$productType = $_product->getAttributeText('headset_product_type');
												if(is_array($productType)) {
													$productType = implode(',', $_product->getAttributeText('headset_product_type'));
												}
												$productType = strpos($productType,'Corded') ? 'corded' : '';
												$productCompatibilityType = $_product->getAttributeText('product_compatability_type');

												?>
												<?php if($productCompatibilityType !== false): ?>
                                                    <a class="works-with-my-phone" data-product-id="<?php echo $_product->getId() ?>" data-product-type="<?php echo $productType?>">Works With My Phone?</a>
												<?php endif?>

											<?php endif?>
                                            <div data-role="add-to-links" class="actions-secondary hide">
												<?php
												if ($addToBlock = $block->getChildBlock('addto')): ?>
													<?= $addToBlock->setProduct($_product)->getChildHtml() ?>
												<?php
												endif; ?>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="grid-x grid-margin-x align-middle">
                                        <div class="cell small-12 medium-6 text-left">
                                            <a href="<?= /* @escapeNotVerified */$_product->getProductUrl() ?>" class="button grey more-info">More Info</a>
                                        </div>
                                        <div class="cell small-12 medium-6 text-right">
                                            <div class="product-item-inner">
                                                <div class="product actions product-item-actions">
                                                    <div class="actions-primary">
                                                        <div class="actions-primary">
															<?php
															if ($_product->isSaleable()): ?>
																<?php
																$postParams = $block->getAddToCartPostParams($_product); ?>
                                                                <form class="<?php echo $_product->getId() ?>" data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */
																$postParams['action'] ?>" method="post">
                                                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */
																	$postParams['data']['product'] ?>">
                                                                    <input type="hidden" name="<?= /* @escapeNotVerified */
																	Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */
																	$postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">

																	<?php
																	if ($stockHelper->isProductQtySalable($_product)) : ?>
																		<?= $block->getBlockHtml('formkey') ?>
                                                                        <button type="submit"
                                                                                title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                                class="action tocart primary button green rounded">
                                                                        <span><?= /* @escapeNotVerified */
																			__('Add to Cart') ?></span>
                                                                        </button>
																	<?php else: ?>
																		<?php if ($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE):?>
                                                                            <button type="submit"
                                                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                                    class="action tocart primary button green rounded">
                                                                        <span><?= /* @escapeNotVerified */
																			__('Add to Cart') ?></span>
                                                                            </button>
																		<?php else:?>
                                                                            <a
                                                                                title="Call To Order"
                                                                                class="action primary top-cart button green rounded not-available"
                                                                                id="product-addtocart-button"
                                                                                data-open="addToCartDisableNotice">
                                                                                Call To Order
                                                                            </a>
																		<?php endif ?>
																	<?php endif ?>
                                                                </form>
															<?php else: ?>
																<?php
																if ($_product->isAvailable()): ?>
                                                                    <div class="stock available">
                                                                    <span><?= /* @escapeNotVerified */
																		__('In stock') ?></span></div>
																<?php else: ?>
																	<?php if($_product->getDiscontinued()):?>
                                                                        <div class="stock unavailable">
                                                                            <a href="<?= /* @escapeNotVerified */$_product->getProductUrl() ?>" class="button grey more-info">Discontinued</a>
                                                                        </div>
																	<?php else:?>
                                                                        <div class="stock unavailable">
                                                                            <a
                                                                                    title="Call To Order"
                                                                                    class="action primary top-cart button green rounded not-available"
                                                                                    id="product-addtocart-button"
                                                                                    data-open="addToCartDisableNotice">
                                                                                Call To Order
                                                                            </a>
                                                                        </div>
																	<?php endif?>
																<?php endif; ?>
															<?php endif; ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                </li>
			<?php endforeach; ?>
        </ol>
    </div>`
	<?php
	if ( ! $block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */$_product->getSku() ?>"
                }
            }
        }
        </script>
	<?php endif; ?>
<?php endif; ?>

